// Code generated by protoc-gen-go. DO NOT EDIT.
// source: store.proto

package store

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RecordedEvent struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Stream               []byte   `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	Version              uint32   `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Data                 []byte   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Metadata             []byte   `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CausationId          []byte   `protobuf:"bytes,7,opt,name=causation_id,json=causationId,proto3" json:"causation_id,omitempty"`
	CorrelationId        []byte   `protobuf:"bytes,8,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	AddedAt              int64    `protobuf:"varint,9,opt,name=added_at,json=addedAt,proto3" json:"added_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordedEvent) Reset()         { *m = RecordedEvent{} }
func (m *RecordedEvent) String() string { return proto.CompactTextString(m) }
func (*RecordedEvent) ProtoMessage()    {}
func (*RecordedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{0}
}

func (m *RecordedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordedEvent.Unmarshal(m, b)
}
func (m *RecordedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordedEvent.Marshal(b, m, deterministic)
}
func (m *RecordedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordedEvent.Merge(m, src)
}
func (m *RecordedEvent) XXX_Size() int {
	return xxx_messageInfo_RecordedEvent.Size(m)
}
func (m *RecordedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_RecordedEvent proto.InternalMessageInfo

func (m *RecordedEvent) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *RecordedEvent) GetStream() []byte {
	if m != nil {
		return m.Stream
	}
	return nil
}

func (m *RecordedEvent) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *RecordedEvent) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *RecordedEvent) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RecordedEvent) GetMetadata() []byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *RecordedEvent) GetCausationId() []byte {
	if m != nil {
		return m.CausationId
	}
	return nil
}

func (m *RecordedEvent) GetCorrelationId() []byte {
	if m != nil {
		return m.CorrelationId
	}
	return nil
}

func (m *RecordedEvent) GetAddedAt() int64 {
	if m != nil {
		return m.AddedAt
	}
	return 0
}

type AddRequest struct {
	Stream               []byte              `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	Version              uint32              `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Events               []*AddRequest_Event `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{1}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetStream() []byte {
	if m != nil {
		return m.Stream
	}
	return nil
}

func (m *AddRequest) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *AddRequest) GetEvents() []*AddRequest_Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type AddRequest_Event struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Metadata             []byte   `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CausationId          []byte   `protobuf:"bytes,4,opt,name=causation_id,json=causationId,proto3" json:"causation_id,omitempty"`
	CorrelationId        []byte   `protobuf:"bytes,5,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRequest_Event) Reset()         { *m = AddRequest_Event{} }
func (m *AddRequest_Event) String() string { return proto.CompactTextString(m) }
func (*AddRequest_Event) ProtoMessage()    {}
func (*AddRequest_Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{1, 0}
}

func (m *AddRequest_Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest_Event.Unmarshal(m, b)
}
func (m *AddRequest_Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest_Event.Marshal(b, m, deterministic)
}
func (m *AddRequest_Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest_Event.Merge(m, src)
}
func (m *AddRequest_Event) XXX_Size() int {
	return xxx_messageInfo_AddRequest_Event.Size(m)
}
func (m *AddRequest_Event) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest_Event.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest_Event proto.InternalMessageInfo

func (m *AddRequest_Event) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AddRequest_Event) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *AddRequest_Event) GetMetadata() []byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *AddRequest_Event) GetCausationId() []byte {
	if m != nil {
		return m.CausationId
	}
	return nil
}

func (m *AddRequest_Event) GetCorrelationId() []byte {
	if m != nil {
		return m.CorrelationId
	}
	return nil
}

type AddResponse struct {
	Events               []*RecordedEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{2}
}

func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (m *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(m, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

func (m *AddResponse) GetEvents() []*RecordedEvent {
	if m != nil {
		return m.Events
	}
	return nil
}

func init() {
	proto.RegisterType((*RecordedEvent)(nil), "store.RecordedEvent")
	proto.RegisterType((*AddRequest)(nil), "store.AddRequest")
	proto.RegisterType((*AddRequest_Event)(nil), "store.AddRequest.Event")
	proto.RegisterType((*AddResponse)(nil), "store.AddResponse")
}

func init() { proto.RegisterFile("store.proto", fileDescriptor_98bbca36ef968dfc) }

var fileDescriptor_98bbca36ef968dfc = []byte{
	// 346 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4e, 0xea, 0x40,
	0x14, 0x86, 0xef, 0xb4, 0xb4, 0x85, 0x53, 0x20, 0xb9, 0x93, 0x9b, 0x7b, 0xe7, 0xb2, 0xaa, 0x4d,
	0x4c, 0xba, 0x30, 0x35, 0xc1, 0xa5, 0x6e, 0x30, 0x71, 0xc1, 0xb6, 0xee, 0xdc, 0x90, 0x91, 0x73,
	0x16, 0x4d, 0xa4, 0x83, 0x9d, 0x81, 0xc4, 0x27, 0xf0, 0x09, 0x7c, 0x59, 0x57, 0x86, 0x53, 0xa8,
	0x10, 0x21, 0xba, 0x9b, 0xff, 0xeb, 0xc9, 0x74, 0xfe, 0x2f, 0x07, 0x62, 0xeb, 0x4c, 0x4d, 0xf9,
	0xb2, 0x36, 0xce, 0xc8, 0x80, 0x43, 0xfa, 0x2e, 0x60, 0x50, 0xd0, 0xdc, 0xd4, 0x48, 0x78, 0xb7,
	0xa6, 0xca, 0xc9, 0x21, 0x78, 0x25, 0x2a, 0x91, 0x88, 0xac, 0x5f, 0x78, 0x25, 0xca, 0xbf, 0x10,
	0x5a, 0x57, 0x93, 0x5e, 0x28, 0x8f, 0xd9, 0x36, 0x49, 0x05, 0xd1, 0x9a, 0x6a, 0x5b, 0x9a, 0x4a,
	0xf9, 0x89, 0xc8, 0x06, 0xc5, 0x2e, 0x4a, 0x09, 0x1d, 0xf7, 0xb2, 0x24, 0xd5, 0x49, 0x44, 0xd6,
	0x2b, 0xf8, 0xbc, 0x61, 0xa8, 0x9d, 0x56, 0x01, 0xdf, 0xc1, 0x67, 0x39, 0x82, 0xee, 0x82, 0x9c,
	0x66, 0x1e, 0x32, 0x6f, 0xb3, 0x3c, 0x83, 0xfe, 0x5c, 0xaf, 0xac, 0x76, 0xa5, 0xa9, 0x66, 0x25,
	0xaa, 0x88, 0xbf, 0xc7, 0x2d, 0x9b, 0xa2, 0x3c, 0x87, 0xe1, 0xdc, 0xd4, 0x35, 0x3d, 0xb5, 0x43,
	0x5d, 0x1e, 0x1a, 0xec, 0xd1, 0x29, 0xca, 0xff, 0xd0, 0xd5, 0x88, 0x84, 0x33, 0xed, 0x54, 0x2f,
	0x11, 0x99, 0x5f, 0x44, 0x9c, 0x27, 0x2e, 0x7d, 0xf5, 0x00, 0x26, 0x88, 0x05, 0x3d, 0xaf, 0xc8,
	0xba, 0xbd, 0xa6, 0xe2, 0x54, 0x53, 0xef, 0xb0, 0xe9, 0x25, 0x84, 0xb4, 0x91, 0x66, 0x95, 0x9f,
	0xf8, 0x59, 0x3c, 0xfe, 0x97, 0x37, 0x8a, 0x3f, 0x2f, 0xcd, 0x59, 0x6a, 0xb1, 0x1d, 0x1b, 0xbd,
	0x09, 0x08, 0x1a, 0xcd, 0x3b, 0x49, 0xe2, 0x88, 0x24, 0xef, 0x84, 0x24, 0xff, 0x1b, 0x49, 0x9d,
	0x9f, 0x48, 0x0a, 0x8e, 0x48, 0x4a, 0xaf, 0x21, 0xe6, 0x37, 0xdb, 0xa5, 0xa9, 0x2c, 0xc9, 0x8b,
	0xb6, 0x97, 0xe0, 0x5e, 0x7f, 0xb6, 0xbd, 0x0e, 0x36, 0x65, 0x57, 0x6a, 0x7c, 0x03, 0xc0, 0xe0,
	0x7e, 0x33, 0x23, 0x73, 0xf0, 0x27, 0x88, 0xf2, 0xf7, 0x17, 0x15, 0x23, 0xb9, 0x8f, 0x9a, 0x3f,
	0xa5, 0xbf, 0x6e, 0xa3, 0x87, 0x66, 0x15, 0x1f, 0x43, 0x5e, 0xcc, 0xab, 0x8f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xb3, 0x7d, 0xfd, 0xad, 0xa7, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EventStoreClient is the client API for EventStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventStoreClient interface {
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
}

type eventStoreClient struct {
	cc *grpc.ClientConn
}

func NewEventStoreClient(cc *grpc.ClientConn) EventStoreClient {
	return &eventStoreClient{cc}
}

func (c *eventStoreClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, "/store.EventStore/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventStoreServer is the server API for EventStore service.
type EventStoreServer interface {
	Add(context.Context, *AddRequest) (*AddResponse, error)
}

// UnimplementedEventStoreServer can be embedded to have forward compatible implementations.
type UnimplementedEventStoreServer struct {
}

func (*UnimplementedEventStoreServer) Add(ctx context.Context, req *AddRequest) (*AddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}

func RegisterEventStoreServer(s *grpc.Server, srv EventStoreServer) {
	s.RegisterService(&_EventStore_serviceDesc, srv)
}

func _EventStore_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventStoreServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/store.EventStore/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventStoreServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EventStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "store.EventStore",
	HandlerType: (*EventStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _EventStore_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "store.proto",
}
