version: "3"

services:
  node1:
    build: .
    ports:
      - 3000:3000
    environment:
      - NODE_ID=node1
      - FOLLOWERS=node2@node2:6544,node3@node3:6544

  node2:
    build: .
    environment:
      - NODE_ID=node2

  node3:
    build: .
    environment:
      - NODE_ID=node3
