version: "3"

services:
  etcd:
    image: bitnami/etcd:latest
    ports:
      - 2379:2379
      - 2380:2380
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes

  prometheus:
    image: prom/prometheus:v2.1.0
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  node1:
    build: .
    ports:
      - 6543:6543

  node2:
    build: .

  node3:
    build: .
