version: "3"

services:
  postgres:
    image: bitnami/postgresql:13
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_PASSWORD=password

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    environment: 
      - PGADMIN_DEFAULT_EMAIL=user@example.com
      - PGADMIN_DEFAULT_PASSWORD=password