version: "3"

services:
  postgres:
    image: bitnami/postgresql:13
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_PASSWORD=password

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    environment: 
      - PGADMIN_DEFAULT_EMAIL=user@example.com
      - PGADMIN_DEFAULT_PASSWORD=password

  cassandra1:
    image: docker.io/bitnami/cassandra:3
    ports:
      - "7000:7000"
      - "9042:9042"
    environment:
      - CASSANDRA_SEEDS=cassandra2,cassandra3
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra

  cassandra2:
    image: docker.io/bitnami/cassandra:3
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra3
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra

  cassandra3:
    image: docker.io/bitnami/cassandra:3
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra