version: "3"

services:
  node1:
    container_name: eventflowdb1
    build: .
    restart: unless-stopped
    environment:
      - EXISTING_NODES=node2,node3
      - EVENTS_FILE=/var/lib/eventflowdb/events.db
    volumes:
      - node1:/var/lib/eventflowdb

  node2:
    container_name: eventflowdb2
    build: .
    restart: unless-stopped
    environment:
      - EXISTING_NODES=node1,node3
      - EVENTS_FILE=/var/lib/eventflowdb/events.db
    volumes:
      - node2:/var/lib/eventflowdb

  # node3:
  #   container_name: eventflowdb3
  #   build: .
  #   restart: unless-stopped
  #   environment:
  #     - EXISTING_NODES=node1,node2
  #     - EVENTS_FILE=/var/lib/eventflowdb/events.db
  #   volumes:
  #     - node3:/var/lib/eventflowdb

volumes:
  node1:
  node2:
  node3:
