version: "3"

services:
  node1:
    container_name: eventflowdb1
    image: eventflowdb
    # restart: unless-stopped
    environment:
      - RAFT_LOCAL_ID=node1
      - RAFT_ADVR_ADDR=node1:6542
    volumes:
      - node1:/var/lib/eventflowdb

  node2:
    container_name: eventflowdb2
    image: eventflowdb
    # restart: unless-stopped
    environment:
      - RAFT_LOCAL_ID=node2
      - RAFT_ADVR_ADDR=node2:6542
    volumes:
      - node2:/var/lib/eventflowdb

  node3:
    container_name: eventflowdb3
    image: eventflowdb
    # restart: unless-stopped
    environment:
      - RAFT_LOCAL_ID=node3
      - RAFT_ADVR_ADDR=node3:6542
      - RAFT_BOOTSTRAP=true
    volumes:
      - node3:/var/lib/eventflowdb

volumes:
  node1:
  node2:
  node3:
