POST http://127.0.0.1:3000/add
Content-Type: application/json

{
    "stream": "961b8c65-58c5-4e7a-9844-fd03b09e7e5b",
    "version": 0,
    "events": [
        {
            "type": "TestEvent"
        }
    ]
}