// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/store.proto

package store

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RecordedEvent struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Stream               []byte   `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	Version              uint32   `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Data                 []byte   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Metadata             []byte   `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CausationId          []byte   `protobuf:"bytes,7,opt,name=causation_id,json=causationId,proto3" json:"causation_id,omitempty"`
	CorrelationId        []byte   `protobuf:"bytes,8,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	AddedAt              int64    `protobuf:"varint,9,opt,name=added_at,json=addedAt,proto3" json:"added_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordedEvent) Reset()         { *m = RecordedEvent{} }
func (m *RecordedEvent) String() string { return proto.CompactTextString(m) }
func (*RecordedEvent) ProtoMessage()    {}
func (*RecordedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f39e0831e20e871, []int{0}
}

func (m *RecordedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordedEvent.Unmarshal(m, b)
}
func (m *RecordedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordedEvent.Marshal(b, m, deterministic)
}
func (m *RecordedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordedEvent.Merge(m, src)
}
func (m *RecordedEvent) XXX_Size() int {
	return xxx_messageInfo_RecordedEvent.Size(m)
}
func (m *RecordedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_RecordedEvent proto.InternalMessageInfo

func (m *RecordedEvent) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *RecordedEvent) GetStream() []byte {
	if m != nil {
		return m.Stream
	}
	return nil
}

func (m *RecordedEvent) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *RecordedEvent) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *RecordedEvent) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RecordedEvent) GetMetadata() []byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *RecordedEvent) GetCausationId() []byte {
	if m != nil {
		return m.CausationId
	}
	return nil
}

func (m *RecordedEvent) GetCorrelationId() []byte {
	if m != nil {
		return m.CorrelationId
	}
	return nil
}

func (m *RecordedEvent) GetAddedAt() int64 {
	if m != nil {
		return m.AddedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*RecordedEvent)(nil), "store.RecordedEvent")
}

func init() { proto.RegisterFile("proto/store.proto", fileDescriptor_3f39e0831e20e871) }

var fileDescriptor_3f39e0831e20e871 = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0xe5, 0xb4, 0x4d, 0xd2, 0xa3, 0xa9, 0xc4, 0x0d, 0xc8, 0x30, 0x05, 0x24, 0xa4, 0x4c,
	0x30, 0xf0, 0x04, 0x0c, 0x0c, 0x5d, 0xfd, 0x02, 0xd5, 0x91, 0xbb, 0xc1, 0x12, 0x8d, 0x2b, 0xfb,
	0x88, 0xc4, 0xab, 0x33, 0x21, 0x4e, 0x10, 0x75, 0xfb, 0xbe, 0xcf, 0xbf, 0x3c, 0x1c, 0x5c, 0x9f,
	0x73, 0xd2, 0xf4, 0x5c, 0x34, 0x65, 0x79, 0x32, 0xc6, 0x8d, 0xc9, 0xc3, 0xb7, 0x83, 0x2e, 0xc8,
	0x98, 0x32, 0x0b, 0xbf, 0xcd, 0x32, 0x29, 0xee, 0xa1, 0x8a, 0xec, 0x5d, 0xef, 0x86, 0x5d, 0xa8,
	0x22, 0xe3, 0x0d, 0xd4, 0x45, 0xb3, 0xd0, 0xc9, 0x57, 0xd6, 0xfe, 0x0c, 0x3d, 0x34, 0xb3, 0xe4,
	0x12, 0xd3, 0xe4, 0x57, 0xbd, 0x1b, 0xba, 0xf0, 0xaf, 0x88, 0xb0, 0xd6, 0xaf, 0xb3, 0xf8, 0x75,
	0xef, 0x86, 0x6d, 0x30, 0xfe, 0x6d, 0x4c, 0x4a, 0x7e, 0x63, 0x7f, 0x18, 0xe3, 0x1d, 0xb4, 0x27,
	0x51, 0xb2, 0x5e, 0x5b, 0x5f, 0x1c, 0xef, 0x61, 0x37, 0xd2, 0x67, 0x21, 0x8d, 0x69, 0x3a, 0x46,
	0xf6, 0x8d, 0xbd, 0x5f, 0x2d, 0xed, 0xc0, 0xf8, 0x08, 0xfb, 0x31, 0xe5, 0x2c, 0x1f, 0xcb, 0xa8,
	0xb5, 0x51, 0x77, 0x51, 0x0f, 0x8c, 0xb7, 0xd0, 0x12, 0xb3, 0xf0, 0x91, 0xd4, 0x6f, 0x7b, 0x37,
	0xac, 0x42, 0x63, 0xfe, 0xaa, 0xef, 0xb5, 0x9d, 0xe2, 0xe5, 0x27, 0x00, 0x00, 0xff, 0xff, 0xd9,
	0xe7, 0x28, 0xbd, 0x1f, 0x01, 0x00, 0x00,
}
