// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Cluster struct {
	Leader string `json:"leader"`
	Size   int    `json:"size"`
}

type Diagnostics struct {
	Uptime   int `json:"uptime"`
	UptimeMs int `json:"uptimeMs"`
}

type Event struct {
	ID            string    `json:"id"`
	Stream        string    `json:"stream"`
	Version       int       `json:"version"`
	Type          string    `json:"type"`
	Data          string    `json:"data"`
	Metadata      string    `json:"metadata"`
	CausationID   string    `json:"causation_id"`
	CorrelationID string    `json:"correlation_id"`
	AddedAt       time.Time `json:"added_at"`
}
