// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cluster.proto

package cluster

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClusterNode struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 uint32   `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterNode) Reset()         { *m = ClusterNode{} }
func (m *ClusterNode) String() string { return proto.CompactTextString(m) }
func (*ClusterNode) ProtoMessage()    {}
func (*ClusterNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_3cfb3b8ec240c376, []int{0}
}

func (m *ClusterNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterNode.Unmarshal(m, b)
}
func (m *ClusterNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterNode.Marshal(b, m, deterministic)
}
func (m *ClusterNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterNode.Merge(m, src)
}
func (m *ClusterNode) XXX_Size() int {
	return xxx_messageInfo_ClusterNode.Size(m)
}
func (m *ClusterNode) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterNode.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterNode proto.InternalMessageInfo

func (m *ClusterNode) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *ClusterNode) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *ClusterNode) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type GetHealthScoreRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHealthScoreRequest) Reset()         { *m = GetHealthScoreRequest{} }
func (m *GetHealthScoreRequest) String() string { return proto.CompactTextString(m) }
func (*GetHealthScoreRequest) ProtoMessage()    {}
func (*GetHealthScoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3cfb3b8ec240c376, []int{1}
}

func (m *GetHealthScoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHealthScoreRequest.Unmarshal(m, b)
}
func (m *GetHealthScoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHealthScoreRequest.Marshal(b, m, deterministic)
}
func (m *GetHealthScoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHealthScoreRequest.Merge(m, src)
}
func (m *GetHealthScoreRequest) XXX_Size() int {
	return xxx_messageInfo_GetHealthScoreRequest.Size(m)
}
func (m *GetHealthScoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHealthScoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHealthScoreRequest proto.InternalMessageInfo

type GetHealthScoreResponse struct {
	Healthscore          int32    `protobuf:"varint,1,opt,name=healthscore,proto3" json:"healthscore,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHealthScoreResponse) Reset()         { *m = GetHealthScoreResponse{} }
func (m *GetHealthScoreResponse) String() string { return proto.CompactTextString(m) }
func (*GetHealthScoreResponse) ProtoMessage()    {}
func (*GetHealthScoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3cfb3b8ec240c376, []int{2}
}

func (m *GetHealthScoreResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHealthScoreResponse.Unmarshal(m, b)
}
func (m *GetHealthScoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHealthScoreResponse.Marshal(b, m, deterministic)
}
func (m *GetHealthScoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHealthScoreResponse.Merge(m, src)
}
func (m *GetHealthScoreResponse) XXX_Size() int {
	return xxx_messageInfo_GetHealthScoreResponse.Size(m)
}
func (m *GetHealthScoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHealthScoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetHealthScoreResponse proto.InternalMessageInfo

func (m *GetHealthScoreResponse) GetHealthscore() int32 {
	if m != nil {
		return m.Healthscore
	}
	return 0
}

type GetNodesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodesRequest) Reset()         { *m = GetNodesRequest{} }
func (m *GetNodesRequest) String() string { return proto.CompactTextString(m) }
func (*GetNodesRequest) ProtoMessage()    {}
func (*GetNodesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3cfb3b8ec240c376, []int{3}
}

func (m *GetNodesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodesRequest.Unmarshal(m, b)
}
func (m *GetNodesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodesRequest.Marshal(b, m, deterministic)
}
func (m *GetNodesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodesRequest.Merge(m, src)
}
func (m *GetNodesRequest) XXX_Size() int {
	return xxx_messageInfo_GetNodesRequest.Size(m)
}
func (m *GetNodesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodesRequest proto.InternalMessageInfo

type GetNodesResponse struct {
	Nodes                []*ClusterNode `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetNodesResponse) Reset()         { *m = GetNodesResponse{} }
func (m *GetNodesResponse) String() string { return proto.CompactTextString(m) }
func (*GetNodesResponse) ProtoMessage()    {}
func (*GetNodesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3cfb3b8ec240c376, []int{4}
}

func (m *GetNodesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodesResponse.Unmarshal(m, b)
}
func (m *GetNodesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodesResponse.Marshal(b, m, deterministic)
}
func (m *GetNodesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodesResponse.Merge(m, src)
}
func (m *GetNodesResponse) XXX_Size() int {
	return xxx_messageInfo_GetNodesResponse.Size(m)
}
func (m *GetNodesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodesResponse proto.InternalMessageInfo

func (m *GetNodesResponse) GetNodes() []*ClusterNode {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func init() {
	proto.RegisterType((*ClusterNode)(nil), "cluster.ClusterNode")
	proto.RegisterType((*GetHealthScoreRequest)(nil), "cluster.GetHealthScoreRequest")
	proto.RegisterType((*GetHealthScoreResponse)(nil), "cluster.GetHealthScoreResponse")
	proto.RegisterType((*GetNodesRequest)(nil), "cluster.GetNodesRequest")
	proto.RegisterType((*GetNodesResponse)(nil), "cluster.GetNodesResponse")
}

func init() { proto.RegisterFile("cluster.proto", fileDescriptor_3cfb3b8ec240c376) }

var fileDescriptor_3cfb3b8ec240c376 = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x71, 0x4a, 0x29, 0xbd, 0xa8, 0x01, 0x4e, 0xfc, 0x31, 0x1d, 0x20, 0xf2, 0x14, 0x31,
	0x74, 0x28, 0x1b, 0x03, 0x12, 0x30, 0x14, 0x09, 0x89, 0xc1, 0xd9, 0xd8, 0x4a, 0x72, 0x52, 0x23,
	0x55, 0xb5, 0xb1, 0x5d, 0x3e, 0x13, 0x1f, 0x13, 0xc5, 0x89, 0x21, 0xa0, 0x74, 0xf3, 0xfd, 0xee,
	0xe9, 0xf9, 0x3d, 0x1d, 0x4c, 0x8a, 0xf5, 0xd6, 0x3a, 0x32, 0x33, 0x6d, 0x94, 0x53, 0x38, 0x6a,
	0x47, 0xf1, 0x02, 0xf1, 0x53, 0xf3, 0x7c, 0x55, 0x25, 0x61, 0x02, 0x51, 0xa5, 0x39, 0x4b, 0x59,
	0x36, 0x96, 0x51, 0xa5, 0x11, 0x61, 0x5f, 0x2b, 0xe3, 0x78, 0x94, 0xb2, 0x6c, 0x22, 0xfd, 0x1b,
	0x39, 0x8c, 0x96, 0x65, 0x69, 0xc8, 0x5a, 0x3e, 0xf0, 0xc2, 0x30, 0x8a, 0x0b, 0x38, 0x5b, 0x90,
	0x7b, 0xa6, 0xe5, 0xda, 0xad, 0xf2, 0x42, 0x19, 0x92, 0xf4, 0xb1, 0x25, 0xeb, 0xc4, 0x1d, 0x9c,
	0xff, 0x5f, 0x58, 0xad, 0x36, 0x96, 0x30, 0x85, 0x78, 0xe5, 0xb1, 0xad, 0xb1, 0xff, 0x79, 0x28,
	0xbb, 0x48, 0x9c, 0xc0, 0xd1, 0x82, 0x5c, 0x9d, 0xce, 0x06, 0xbb, 0x7b, 0x38, 0xfe, 0x45, 0xad,
	0xd1, 0x0d, 0x0c, 0x37, 0x35, 0xe0, 0x2c, 0x1d, 0x64, 0xf1, 0xfc, 0x74, 0x16, 0x0a, 0x77, 0xea,
	0xc9, 0x46, 0x32, 0xff, 0x62, 0x90, 0xb4, 0x38, 0x27, 0xf3, 0x59, 0x15, 0x84, 0x39, 0x24, 0x7f,
	0x13, 0xe2, 0xd5, 0x8f, 0x43, 0x6f, 0xa7, 0xe9, 0xf5, 0xce, 0x7d, 0x93, 0x48, 0xec, 0xe1, 0x03,
	0x1c, 0x86, 0x9c, 0xc8, 0xbb, 0xf2, 0x6e, 0x9b, 0xe9, 0x65, 0xcf, 0x26, 0x58, 0x3c, 0x8e, 0xdf,
	0xc2, 0xa9, 0xde, 0x0f, 0xfc, 0xe9, 0x6e, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x95, 0xb6, 0x3c,
	0xab, 0xcb, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ClusterServiceClient is the client API for ClusterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClusterServiceClient interface {
	GetHealthScore(ctx context.Context, in *GetHealthScoreRequest, opts ...grpc.CallOption) (*GetHealthScoreResponse, error)
	GetNodes(ctx context.Context, in *GetNodesRequest, opts ...grpc.CallOption) (*GetNodesResponse, error)
}

type clusterServiceClient struct {
	cc *grpc.ClientConn
}

func NewClusterServiceClient(cc *grpc.ClientConn) ClusterServiceClient {
	return &clusterServiceClient{cc}
}

func (c *clusterServiceClient) GetHealthScore(ctx context.Context, in *GetHealthScoreRequest, opts ...grpc.CallOption) (*GetHealthScoreResponse, error) {
	out := new(GetHealthScoreResponse)
	err := c.cc.Invoke(ctx, "/cluster.ClusterService/GetHealthScore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterServiceClient) GetNodes(ctx context.Context, in *GetNodesRequest, opts ...grpc.CallOption) (*GetNodesResponse, error) {
	out := new(GetNodesResponse)
	err := c.cc.Invoke(ctx, "/cluster.ClusterService/GetNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClusterServiceServer is the server API for ClusterService service.
type ClusterServiceServer interface {
	GetHealthScore(context.Context, *GetHealthScoreRequest) (*GetHealthScoreResponse, error)
	GetNodes(context.Context, *GetNodesRequest) (*GetNodesResponse, error)
}

// UnimplementedClusterServiceServer can be embedded to have forward compatible implementations.
type UnimplementedClusterServiceServer struct {
}

func (*UnimplementedClusterServiceServer) GetHealthScore(ctx context.Context, req *GetHealthScoreRequest) (*GetHealthScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHealthScore not implemented")
}
func (*UnimplementedClusterServiceServer) GetNodes(ctx context.Context, req *GetNodesRequest) (*GetNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodes not implemented")
}

func RegisterClusterServiceServer(s *grpc.Server, srv ClusterServiceServer) {
	s.RegisterService(&_ClusterService_serviceDesc, srv)
}

func _ClusterService_GetHealthScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHealthScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).GetHealthScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cluster.ClusterService/GetHealthScore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).GetHealthScore(ctx, req.(*GetHealthScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterService_GetNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).GetNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cluster.ClusterService/GetNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).GetNodes(ctx, req.(*GetNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ClusterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cluster.ClusterService",
	HandlerType: (*ClusterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHealthScore",
			Handler:    _ClusterService_GetHealthScore_Handler,
		},
		{
			MethodName: "GetNodes",
			Handler:    _ClusterService_GetNodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cluster.proto",
}
