// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fsm.proto

package cluster

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Stream               []byte   `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	Version              uint32   `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Data                 []byte   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Metadata             []byte   `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CausationId          []byte   `protobuf:"bytes,7,opt,name=causation_id,json=causationId,proto3" json:"causation_id,omitempty"`
	CorrelationId        []byte   `protobuf:"bytes,8,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	AddedAt              uint64   `protobuf:"varint,9,opt,name=added_at,json=addedAt,proto3" json:"added_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef5b9a5dc540ad10, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Event) GetStream() []byte {
	if m != nil {
		return m.Stream
	}
	return nil
}

func (m *Event) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Event) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Event) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Event) GetMetadata() []byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Event) GetCausationId() []byte {
	if m != nil {
		return m.CausationId
	}
	return nil
}

func (m *Event) GetCorrelationId() []byte {
	if m != nil {
		return m.CorrelationId
	}
	return nil
}

func (m *Event) GetAddedAt() uint64 {
	if m != nil {
		return m.AddedAt
	}
	return 0
}

type Stream struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Events               [][]byte `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	AddedAt              uint64   `protobuf:"varint,3,opt,name=added_at,json=addedAt,proto3" json:"added_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stream) Reset()         { *m = Stream{} }
func (m *Stream) String() string { return proto.CompactTextString(m) }
func (*Stream) ProtoMessage()    {}
func (*Stream) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef5b9a5dc540ad10, []int{1}
}

func (m *Stream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stream.Unmarshal(m, b)
}
func (m *Stream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stream.Marshal(b, m, deterministic)
}
func (m *Stream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stream.Merge(m, src)
}
func (m *Stream) XXX_Size() int {
	return xxx_messageInfo_Stream.Size(m)
}
func (m *Stream) XXX_DiscardUnknown() {
	xxx_messageInfo_Stream.DiscardUnknown(m)
}

var xxx_messageInfo_Stream proto.InternalMessageInfo

func (m *Stream) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Stream) GetEvents() [][]byte {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *Stream) GetAddedAt() uint64 {
	if m != nil {
		return m.AddedAt
	}
	return 0
}

type AddCommand struct {
	Stream               []byte              `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	Version              uint32              `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Events               []*AddCommand_Event `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *AddCommand) Reset()         { *m = AddCommand{} }
func (m *AddCommand) String() string { return proto.CompactTextString(m) }
func (*AddCommand) ProtoMessage()    {}
func (*AddCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef5b9a5dc540ad10, []int{2}
}

func (m *AddCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCommand.Unmarshal(m, b)
}
func (m *AddCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCommand.Marshal(b, m, deterministic)
}
func (m *AddCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCommand.Merge(m, src)
}
func (m *AddCommand) XXX_Size() int {
	return xxx_messageInfo_AddCommand.Size(m)
}
func (m *AddCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCommand.DiscardUnknown(m)
}

var xxx_messageInfo_AddCommand proto.InternalMessageInfo

func (m *AddCommand) GetStream() []byte {
	if m != nil {
		return m.Stream
	}
	return nil
}

func (m *AddCommand) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *AddCommand) GetEvents() []*AddCommand_Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type AddCommand_Event struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Metadata             []byte   `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CausationId          []byte   `protobuf:"bytes,4,opt,name=causation_id,json=causationId,proto3" json:"causation_id,omitempty"`
	CorrelationId        []byte   `protobuf:"bytes,5,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddCommand_Event) Reset()         { *m = AddCommand_Event{} }
func (m *AddCommand_Event) String() string { return proto.CompactTextString(m) }
func (*AddCommand_Event) ProtoMessage()    {}
func (*AddCommand_Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef5b9a5dc540ad10, []int{2, 0}
}

func (m *AddCommand_Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCommand_Event.Unmarshal(m, b)
}
func (m *AddCommand_Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCommand_Event.Marshal(b, m, deterministic)
}
func (m *AddCommand_Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCommand_Event.Merge(m, src)
}
func (m *AddCommand_Event) XXX_Size() int {
	return xxx_messageInfo_AddCommand_Event.Size(m)
}
func (m *AddCommand_Event) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCommand_Event.DiscardUnknown(m)
}

var xxx_messageInfo_AddCommand_Event proto.InternalMessageInfo

func (m *AddCommand_Event) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AddCommand_Event) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *AddCommand_Event) GetMetadata() []byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *AddCommand_Event) GetCausationId() []byte {
	if m != nil {
		return m.CausationId
	}
	return nil
}

func (m *AddCommand_Event) GetCorrelationId() []byte {
	if m != nil {
		return m.CorrelationId
	}
	return nil
}

type ApplyLog struct {
	// Types that are valid to be assigned to Command:
	//	*ApplyLog_Add
	Command              isApplyLog_Command `protobuf_oneof:"Command"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ApplyLog) Reset()         { *m = ApplyLog{} }
func (m *ApplyLog) String() string { return proto.CompactTextString(m) }
func (*ApplyLog) ProtoMessage()    {}
func (*ApplyLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef5b9a5dc540ad10, []int{3}
}

func (m *ApplyLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyLog.Unmarshal(m, b)
}
func (m *ApplyLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyLog.Marshal(b, m, deterministic)
}
func (m *ApplyLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyLog.Merge(m, src)
}
func (m *ApplyLog) XXX_Size() int {
	return xxx_messageInfo_ApplyLog.Size(m)
}
func (m *ApplyLog) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyLog.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyLog proto.InternalMessageInfo

type isApplyLog_Command interface {
	isApplyLog_Command()
}

type ApplyLog_Add struct {
	Add *AddCommand `protobuf:"bytes,1,opt,name=add,proto3,oneof"`
}

func (*ApplyLog_Add) isApplyLog_Command() {}

func (m *ApplyLog) GetCommand() isApplyLog_Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *ApplyLog) GetAdd() *AddCommand {
	if x, ok := m.GetCommand().(*ApplyLog_Add); ok {
		return x.Add
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ApplyLog) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ApplyLog_Add)(nil),
	}
}

func init() {
	proto.RegisterType((*Event)(nil), "cluster.Event")
	proto.RegisterType((*Stream)(nil), "cluster.Stream")
	proto.RegisterType((*AddCommand)(nil), "cluster.AddCommand")
	proto.RegisterType((*AddCommand_Event)(nil), "cluster.AddCommand.Event")
	proto.RegisterType((*ApplyLog)(nil), "cluster.ApplyLog")
}

func init() { proto.RegisterFile("fsm.proto", fileDescriptor_ef5b9a5dc540ad10) }

var fileDescriptor_ef5b9a5dc540ad10 = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0x4b, 0xc3, 0x30,
	0x18, 0xc6, 0x4d, 0xd2, 0xf5, 0xcf, 0xbb, 0x3f, 0x87, 0x08, 0x92, 0xed, 0x54, 0x07, 0x62, 0x4f,
	0x05, 0xe7, 0x5d, 0xd8, 0x44, 0x70, 0xe8, 0xa9, 0xde, 0xbc, 0x8c, 0xb8, 0x44, 0x29, 0xac, 0x4d,
	0x69, 0xb2, 0xc1, 0x3e, 0x82, 0x1f, 0xc0, 0x2f, 0xea, 0x27, 0x90, 0x66, 0x6b, 0xdd, 0xa0, 0x43,
	0x6f, 0x79, 0x9e, 0xbe, 0x3c, 0xcd, 0xf3, 0x7b, 0x03, 0xc1, 0xbb, 0xce, 0xe2, 0xa2, 0x54, 0x46,
	0x51, 0x6f, 0xb9, 0x5a, 0x6b, 0x23, 0xcb, 0xf1, 0x37, 0x82, 0xce, 0xc3, 0x46, 0xe6, 0x86, 0x0e,
	0x00, 0xa7, 0x82, 0xa1, 0x10, 0x45, 0xbd, 0x04, 0xa7, 0x82, 0x5e, 0x80, 0xab, 0x4d, 0x29, 0x79,
	0xc6, 0xb0, 0xf5, 0xf6, 0x8a, 0x32, 0xf0, 0x36, 0xb2, 0xd4, 0xa9, 0xca, 0x19, 0x09, 0x51, 0xd4,
	0x4f, 0x6a, 0x49, 0x29, 0x38, 0x66, 0x5b, 0x48, 0xe6, 0x84, 0x28, 0x0a, 0x12, 0x7b, 0xae, 0x3c,
	0xc1, 0x0d, 0x67, 0x1d, 0x9b, 0x61, 0xcf, 0x74, 0x04, 0x7e, 0x26, 0x0d, 0xb7, 0xbe, 0x6b, 0xfd,
	0x46, 0xd3, 0x4b, 0xe8, 0x2d, 0xf9, 0x5a, 0x73, 0x93, 0xaa, 0x7c, 0x91, 0x0a, 0xe6, 0xd9, 0xef,
	0xdd, 0xc6, 0x9b, 0x0b, 0x7a, 0x05, 0x83, 0xa5, 0x2a, 0x4b, 0xb9, 0x6a, 0x86, 0x7c, 0x3b, 0xd4,
	0x3f, 0x70, 0xe7, 0x82, 0x0e, 0xc1, 0xe7, 0x42, 0x48, 0xb1, 0xe0, 0x86, 0x05, 0x21, 0x8a, 0x9c,
	0xc4, 0xb3, 0x7a, 0x6a, 0xc6, 0x4f, 0xe0, 0xbe, 0xec, 0xca, 0xb4, 0x94, 0x96, 0x15, 0x0d, 0xcd,
	0x70, 0x48, 0xaa, 0xd2, 0x3b, 0x75, 0x14, 0x46, 0x8e, 0xc3, 0x3e, 0x31, 0xc0, 0x54, 0x88, 0x7b,
	0x95, 0x65, 0x3c, 0x3f, 0xc4, 0x86, 0x4e, 0x61, 0xc3, 0xc7, 0xd8, 0x6e, 0x9a, 0x7f, 0x92, 0x90,
	0x44, 0xdd, 0xc9, 0x30, 0xde, 0x2f, 0x27, 0xfe, 0x8d, 0x8d, 0xed, 0x8e, 0xea, 0xeb, 0x8c, 0xbe,
	0x9a, 0xad, 0xd5, 0xcc, 0x51, 0x0b, 0x73, 0x7c, 0x82, 0x39, 0xf9, 0x83, 0xb9, 0xf3, 0x1f, 0xe6,
	0x9d, 0x16, 0xe6, 0xe3, 0x3b, 0xf0, 0xa7, 0x45, 0xb1, 0xda, 0x3e, 0xab, 0x0f, 0x7a, 0x0d, 0x84,
	0x8b, 0x1d, 0xdb, 0xee, 0xe4, 0xbc, 0xa5, 0xd3, 0xe3, 0x59, 0x52, 0x4d, 0xcc, 0x02, 0xf0, 0xf6,
	0xce, 0x2c, 0x78, 0xad, 0x1f, 0xe6, 0x9b, 0x6b, 0x1f, 0xea, 0xed, 0x4f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x95, 0xe3, 0xff, 0x8d, 0xb5, 0x02, 0x00, 0x00,
}
