// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Stream               []byte   `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	Version              uint32   `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Data                 []byte   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Metadata             []byte   `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CausationId          []byte   `protobuf:"bytes,7,opt,name=causation_id,json=causationId,proto3" json:"causation_id,omitempty"`
	CorrelationId        []byte   `protobuf:"bytes,8,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	AddedAt              int64    `protobuf:"varint,9,opt,name=added_at,json=addedAt,proto3" json:"added_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Event) GetStream() []byte {
	if m != nil {
		return m.Stream
	}
	return nil
}

func (m *Event) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Event) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Event) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Event) GetMetadata() []byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Event) GetCausationId() []byte {
	if m != nil {
		return m.CausationId
	}
	return nil
}

func (m *Event) GetCorrelationId() []byte {
	if m != nil {
		return m.CorrelationId
	}
	return nil
}

func (m *Event) GetAddedAt() int64 {
	if m != nil {
		return m.AddedAt
	}
	return 0
}

type AddEventsRequest struct {
	Stream               []byte                        `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	Version              uint32                        `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Events               []*AddEventsRequest_EventData `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *AddEventsRequest) Reset()         { *m = AddEventsRequest{} }
func (m *AddEventsRequest) String() string { return proto.CompactTextString(m) }
func (*AddEventsRequest) ProtoMessage()    {}
func (*AddEventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *AddEventsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddEventsRequest.Unmarshal(m, b)
}
func (m *AddEventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddEventsRequest.Marshal(b, m, deterministic)
}
func (m *AddEventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddEventsRequest.Merge(m, src)
}
func (m *AddEventsRequest) XXX_Size() int {
	return xxx_messageInfo_AddEventsRequest.Size(m)
}
func (m *AddEventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddEventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddEventsRequest proto.InternalMessageInfo

func (m *AddEventsRequest) GetStream() []byte {
	if m != nil {
		return m.Stream
	}
	return nil
}

func (m *AddEventsRequest) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *AddEventsRequest) GetEvents() []*AddEventsRequest_EventData {
	if m != nil {
		return m.Events
	}
	return nil
}

type AddEventsRequest_EventData struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Metadata             []byte   `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CausationId          []byte   `protobuf:"bytes,4,opt,name=causation_id,json=causationId,proto3" json:"causation_id,omitempty"`
	CorrelationId        []byte   `protobuf:"bytes,5,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	AddedAt              int64    `protobuf:"varint,6,opt,name=added_at,json=addedAt,proto3" json:"added_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddEventsRequest_EventData) Reset()         { *m = AddEventsRequest_EventData{} }
func (m *AddEventsRequest_EventData) String() string { return proto.CompactTextString(m) }
func (*AddEventsRequest_EventData) ProtoMessage()    {}
func (*AddEventsRequest_EventData) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1, 0}
}

func (m *AddEventsRequest_EventData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddEventsRequest_EventData.Unmarshal(m, b)
}
func (m *AddEventsRequest_EventData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddEventsRequest_EventData.Marshal(b, m, deterministic)
}
func (m *AddEventsRequest_EventData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddEventsRequest_EventData.Merge(m, src)
}
func (m *AddEventsRequest_EventData) XXX_Size() int {
	return xxx_messageInfo_AddEventsRequest_EventData.Size(m)
}
func (m *AddEventsRequest_EventData) XXX_DiscardUnknown() {
	xxx_messageInfo_AddEventsRequest_EventData.DiscardUnknown(m)
}

var xxx_messageInfo_AddEventsRequest_EventData proto.InternalMessageInfo

func (m *AddEventsRequest_EventData) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AddEventsRequest_EventData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *AddEventsRequest_EventData) GetMetadata() []byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *AddEventsRequest_EventData) GetCausationId() []byte {
	if m != nil {
		return m.CausationId
	}
	return nil
}

func (m *AddEventsRequest_EventData) GetCorrelationId() []byte {
	if m != nil {
		return m.CorrelationId
	}
	return nil
}

func (m *AddEventsRequest_EventData) GetAddedAt() int64 {
	if m != nil {
		return m.AddedAt
	}
	return 0
}

type AddEventsResponse struct {
	Events               []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddEventsResponse) Reset()         { *m = AddEventsResponse{} }
func (m *AddEventsResponse) String() string { return proto.CompactTextString(m) }
func (*AddEventsResponse) ProtoMessage()    {}
func (*AddEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *AddEventsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddEventsResponse.Unmarshal(m, b)
}
func (m *AddEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddEventsResponse.Marshal(b, m, deterministic)
}
func (m *AddEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddEventsResponse.Merge(m, src)
}
func (m *AddEventsResponse) XXX_Size() int {
	return xxx_messageInfo_AddEventsResponse.Size(m)
}
func (m *AddEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddEventsResponse proto.InternalMessageInfo

func (m *AddEventsResponse) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type GetEventsRequest struct {
	Stream               []byte   `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	Version              uint32   `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Limit                uint32   `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventsRequest) Reset()         { *m = GetEventsRequest{} }
func (m *GetEventsRequest) String() string { return proto.CompactTextString(m) }
func (*GetEventsRequest) ProtoMessage()    {}
func (*GetEventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *GetEventsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsRequest.Unmarshal(m, b)
}
func (m *GetEventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsRequest.Marshal(b, m, deterministic)
}
func (m *GetEventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsRequest.Merge(m, src)
}
func (m *GetEventsRequest) XXX_Size() int {
	return xxx_messageInfo_GetEventsRequest.Size(m)
}
func (m *GetEventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsRequest proto.InternalMessageInfo

func (m *GetEventsRequest) GetStream() []byte {
	if m != nil {
		return m.Stream
	}
	return nil
}

func (m *GetEventsRequest) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *GetEventsRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetEventsResponse struct {
	Events               []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventsResponse) Reset()         { *m = GetEventsResponse{} }
func (m *GetEventsResponse) String() string { return proto.CompactTextString(m) }
func (*GetEventsResponse) ProtoMessage()    {}
func (*GetEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *GetEventsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsResponse.Unmarshal(m, b)
}
func (m *GetEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsResponse.Marshal(b, m, deterministic)
}
func (m *GetEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsResponse.Merge(m, src)
}
func (m *GetEventsResponse) XXX_Size() int {
	return xxx_messageInfo_GetEventsResponse.Size(m)
}
func (m *GetEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsResponse proto.InternalMessageInfo

func (m *GetEventsResponse) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type LogEventsRequest struct {
	Offset               []byte   `protobuf:"bytes,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                uint32   `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogEventsRequest) Reset()         { *m = LogEventsRequest{} }
func (m *LogEventsRequest) String() string { return proto.CompactTextString(m) }
func (*LogEventsRequest) ProtoMessage()    {}
func (*LogEventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *LogEventsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogEventsRequest.Unmarshal(m, b)
}
func (m *LogEventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogEventsRequest.Marshal(b, m, deterministic)
}
func (m *LogEventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogEventsRequest.Merge(m, src)
}
func (m *LogEventsRequest) XXX_Size() int {
	return xxx_messageInfo_LogEventsRequest.Size(m)
}
func (m *LogEventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogEventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogEventsRequest proto.InternalMessageInfo

func (m *LogEventsRequest) GetOffset() []byte {
	if m != nil {
		return m.Offset
	}
	return nil
}

func (m *LogEventsRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type LogEventsResponse struct {
	Events               []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogEventsResponse) Reset()         { *m = LogEventsResponse{} }
func (m *LogEventsResponse) String() string { return proto.CompactTextString(m) }
func (*LogEventsResponse) ProtoMessage()    {}
func (*LogEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *LogEventsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogEventsResponse.Unmarshal(m, b)
}
func (m *LogEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogEventsResponse.Marshal(b, m, deterministic)
}
func (m *LogEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogEventsResponse.Merge(m, src)
}
func (m *LogEventsResponse) XXX_Size() int {
	return xxx_messageInfo_LogEventsResponse.Size(m)
}
func (m *LogEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogEventsResponse proto.InternalMessageInfo

func (m *LogEventsResponse) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func init() {
	proto.RegisterType((*Event)(nil), "api.Event")
	proto.RegisterType((*AddEventsRequest)(nil), "api.AddEventsRequest")
	proto.RegisterType((*AddEventsRequest_EventData)(nil), "api.AddEventsRequest.EventData")
	proto.RegisterType((*AddEventsResponse)(nil), "api.AddEventsResponse")
	proto.RegisterType((*GetEventsRequest)(nil), "api.GetEventsRequest")
	proto.RegisterType((*GetEventsResponse)(nil), "api.GetEventsResponse")
	proto.RegisterType((*LogEventsRequest)(nil), "api.LogEventsRequest")
	proto.RegisterType((*LogEventsResponse)(nil), "api.LogEventsResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 433 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0xcd, 0x6e, 0xd3, 0x40,
	0x14, 0x85, 0x3b, 0x76, 0xec, 0xc4, 0xb7, 0x4d, 0x15, 0x46, 0x50, 0x0d, 0xd9, 0x60, 0x2c, 0x21,
	0x79, 0x95, 0x45, 0x59, 0x74, 0xc3, 0x82, 0x22, 0x10, 0xaa, 0xc4, 0xca, 0xdd, 0x75, 0x13, 0x0d,
	0x99, 0x09, 0x1a, 0x29, 0xf1, 0x18, 0xcf, 0x24, 0x12, 0xef, 0x95, 0x97, 0xe0, 0x75, 0x78, 0x02,
	0xe4, 0x6b, 0x67, 0x70, 0x9c, 0x44, 0x09, 0xea, 0xce, 0xe7, 0xf8, 0xfe, 0x9d, 0x4f, 0x96, 0x21,
	0xe2, 0x85, 0x9a, 0x14, 0xa5, 0xb6, 0x9a, 0xfa, 0xbc, 0x50, 0xc9, 0x1f, 0x02, 0xc1, 0x97, 0xb5,
	0xcc, 0x2d, 0xbd, 0x06, 0x4f, 0x09, 0x46, 0x62, 0x92, 0x5e, 0x65, 0x9e, 0x12, 0xf4, 0x06, 0x42,
	0x63, 0x4b, 0xc9, 0x97, 0xcc, 0x43, 0xaf, 0x51, 0x94, 0x41, 0x7f, 0x2d, 0x4b, 0xa3, 0x74, 0xce,
	0xfc, 0x98, 0xa4, 0xc3, 0x6c, 0x2b, 0x29, 0x85, 0x9e, 0xfd, 0x55, 0x48, 0xd6, 0x8b, 0x49, 0x1a,
	0x65, 0xf8, 0x5c, 0x79, 0x82, 0x5b, 0xce, 0x02, 0x9c, 0x81, 0xcf, 0x74, 0x0c, 0x83, 0xa5, 0xb4,
	0x1c, 0xfd, 0x10, 0x7d, 0xa7, 0xe9, 0x5b, 0xb8, 0x9a, 0xf1, 0x95, 0xe1, 0x56, 0xe9, 0x7c, 0xaa,
	0x04, 0xeb, 0xe3, 0xfb, 0x4b, 0xe7, 0x3d, 0x08, 0xfa, 0x0e, 0xae, 0x67, 0xba, 0x2c, 0xe5, 0xc2,
	0x15, 0x0d, 0xb0, 0x68, 0xd8, 0x72, 0x1f, 0x04, 0x7d, 0x0d, 0x03, 0x2e, 0x84, 0x14, 0x53, 0x6e,
	0x59, 0x14, 0x93, 0xd4, 0xcf, 0xfa, 0xa8, 0xef, 0x6d, 0xb2, 0xf1, 0x60, 0x74, 0x2f, 0x04, 0xe6,
	0x36, 0x99, 0xfc, 0xb9, 0x92, 0xc6, 0xb6, 0xf2, 0x92, 0x63, 0x79, 0xbd, 0xdd, 0xbc, 0x77, 0x10,
	0x4a, 0x1c, 0xc1, 0xfc, 0xd8, 0x4f, 0x2f, 0x6f, 0xdf, 0x4c, 0x2a, 0xb8, 0xdd, 0xc1, 0x13, 0x54,
	0x9f, 0xb9, 0xe5, 0x59, 0x53, 0x3e, 0xde, 0x10, 0x88, 0x9c, 0xeb, 0xb0, 0x91, 0x03, 0xd8, 0xbc,
	0x23, 0xd8, 0xfc, 0x13, 0xd8, 0x7a, 0xe7, 0x60, 0x0b, 0x4e, 0x61, 0x0b, 0x77, 0xb1, 0xdd, 0xc1,
	0x8b, 0x56, 0x38, 0x53, 0xe8, 0xdc, 0x48, 0x9a, 0x38, 0x08, 0x04, 0x21, 0x00, 0x42, 0xc0, 0xa2,
	0x6d, 0xde, 0xe4, 0x09, 0x46, 0x5f, 0xa5, 0x7d, 0x2e, 0xee, 0x97, 0x10, 0x2c, 0xd4, 0x52, 0xd9,
	0xe6, 0xb3, 0xab, 0x45, 0x75, 0x54, 0x6b, 0xf6, 0x7f, 0x1c, 0xf5, 0x11, 0x46, 0xdf, 0xf4, 0x8f,
	0xbd, 0xa3, 0xf4, 0x7c, 0x6e, 0xa4, 0xdd, 0x1e, 0x55, 0xab, 0x7f, 0xab, 0xbd, 0xce, 0xea, 0xd6,
	0x84, 0xf3, 0x57, 0xdf, 0xfe, 0x26, 0x30, 0x7c, 0xc4, 0xb8, 0x8f, 0xb2, 0x5c, 0xab, 0x99, 0xa4,
	0x1f, 0x20, 0x72, 0x68, 0xe9, 0xab, 0x83, 0xdf, 0xd1, 0xf8, 0xa6, 0x6b, 0xd7, 0x1b, 0x93, 0x8b,
	0xaa, 0xdb, 0x31, 0x68, 0xba, 0xbb, 0xbc, 0x9b, 0xee, 0x3d, 0x54, 0x75, 0xb7, 0x8b, 0xd1, 0x74,
	0x77, 0xc1, 0x34, 0xdd, 0x7b, 0x69, 0x93, 0x8b, 0x4f, 0xc1, 0x53, 0xf5, 0x1f, 0xf9, 0x1e, 0xe2,
	0x3f, 0xe5, 0xfd, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x07, 0xa4, 0xcd, 0xda, 0x60, 0x04, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StreamServiceClient is the client API for StreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StreamServiceClient interface {
	AddEvents(ctx context.Context, in *AddEventsRequest, opts ...grpc.CallOption) (*AddEventsResponse, error)
	GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsResponse, error)
	LogEvents(ctx context.Context, in *LogEventsRequest, opts ...grpc.CallOption) (*LogEventsResponse, error)
}

type streamServiceClient struct {
	cc *grpc.ClientConn
}

func NewStreamServiceClient(cc *grpc.ClientConn) StreamServiceClient {
	return &streamServiceClient{cc}
}

func (c *streamServiceClient) AddEvents(ctx context.Context, in *AddEventsRequest, opts ...grpc.CallOption) (*AddEventsResponse, error) {
	out := new(AddEventsResponse)
	err := c.cc.Invoke(ctx, "/api.StreamService/AddEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsResponse, error) {
	out := new(GetEventsResponse)
	err := c.cc.Invoke(ctx, "/api.StreamService/GetEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamServiceClient) LogEvents(ctx context.Context, in *LogEventsRequest, opts ...grpc.CallOption) (*LogEventsResponse, error) {
	out := new(LogEventsResponse)
	err := c.cc.Invoke(ctx, "/api.StreamService/LogEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StreamServiceServer is the server API for StreamService service.
type StreamServiceServer interface {
	AddEvents(context.Context, *AddEventsRequest) (*AddEventsResponse, error)
	GetEvents(context.Context, *GetEventsRequest) (*GetEventsResponse, error)
	LogEvents(context.Context, *LogEventsRequest) (*LogEventsResponse, error)
}

// UnimplementedStreamServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStreamServiceServer struct {
}

func (*UnimplementedStreamServiceServer) AddEvents(ctx context.Context, req *AddEventsRequest) (*AddEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddEvents not implemented")
}
func (*UnimplementedStreamServiceServer) GetEvents(ctx context.Context, req *GetEventsRequest) (*GetEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEvents not implemented")
}
func (*UnimplementedStreamServiceServer) LogEvents(ctx context.Context, req *LogEventsRequest) (*LogEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogEvents not implemented")
}

func RegisterStreamServiceServer(s *grpc.Server, srv StreamServiceServer) {
	s.RegisterService(&_StreamService_serviceDesc, srv)
}

func _StreamService_AddEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).AddEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.StreamService/AddEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).AddEvents(ctx, req.(*AddEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_GetEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).GetEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.StreamService/GetEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).GetEvents(ctx, req.(*GetEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamService_LogEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamServiceServer).LogEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.StreamService/LogEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamServiceServer).LogEvents(ctx, req.(*LogEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StreamService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.StreamService",
	HandlerType: (*StreamServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddEvents",
			Handler:    _StreamService_AddEvents_Handler,
		},
		{
			MethodName: "GetEvents",
			Handler:    _StreamService_GetEvents_Handler,
		},
		{
			MethodName: "LogEvents",
			Handler:    _StreamService_LogEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
