name: CI

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  integrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: "1.16.0"
      - name: Run tests
        run: go test -v ./...
      - name: Run build
        run: go build -o server cmd/eventflowdb/main.go