name: CICD

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: "1.16.0"
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
      - name: Run build
        run: go build cmd/server/main.go -o server
      - name: Vet and lint
        run: |
          go vet cmd/server/main.go
          golint cmd/server/main.go
      - name: Run tests
        run: go test -v ./...
