name: CI

on:
  push:
    tags: "*.*.*"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Set short commit hash in env
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.5.0
        with:
          push: true
          tags: |
            ghcr.io/eventflowdb/eventflowdb:${{ env.TAG }}
            ghcr.io/eventflowdb/eventflowdb:latest
