name: CI

on:
  push:
    tags: "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: "1.16.0"
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
      - name: Run build
        run: go build -o server cmd/eventflowdb/main.go
      - name: Vet and lint
        run: |
          go vet cmd/eventflowdb/main.go
          golint cmd/eventflowdb/main.go
      - name: Run tests
        run: go test -v ./...

  push:
    runs-on: ubuntu-latest
    steps:
      - name: Set short commit hash in env
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.5.0
        with:
          push: true
          tags: kajjagtenberg/eventflowdb:${{ env.TAG }}
